version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: appointment-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appointment-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: appointment-backend
    ports:
      - "4000:4000"
    volumes:
      - /src/app/node_modules
      - ./backend:/src/app
    networks:
      - appointment-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: appointment-frontend
    ports:
      - "5173:5173"
    volumes:
      - /src/app/node_modules
      - ./frontend:/src/app
    networks:
      - appointment-network
    depends_on:
      - backend
  
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: appointment-admin
    ports:
      - "5174:5174"
    volumes:
      - /src/app/node_modules
      - ./admin:/src/app
    networks:
      - appointment-network
    depends_on:
      - backend

networks:
  appointment-network:
    driver: bridge

volumes:
  mongo-data:
  node_modules:
